name: sar
description: Schulbroschüren App der Schule am Ried

publish_to: 'none' # Do not remove!

version: 2.5.0+6 # Hier Version der App ändern (die Zahl nach dem + bei jeder Versionsänderung um 1 erhöhen!)

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  cached_network_image: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.7.2+1
  url_launcher: ^6.0.2
  mobile_scanner: ^5.1.1
  package_info_plus: ^8.0.0

dev_dependencies: 
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_background: "#ff253185"
# Command um Launcher Icon zu generieren: flutter pub run flutter_launcher_icons

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/texts/
    - assets/texts/informationen/
    - assets/icon/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
